name: CI - Tests MLOps

env:
    CI: true
    PYTHONPATH: .

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest setuptools wheel
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build -t homecredit_api .
  
  run-container:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run container
        run: |
          docker run -d -p 8000:8000 --name homecredit_api homecredit_api
          sleep 10
          curl http://localhost:8000/health


  deploy:
    runs-on: ubuntu-latest
    needs: run-container
    if: github.ref == 'refs/heads/main'

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://Fouxy84:$HF_TOKEN@huggingface.co/spaces/Fouxy84/MLops_2
          git push --force space main